// SPDX-FileCopyrightText: 2026 StillJC
// SPDX-License-Identifier: GPL-3.0-only

#pragma once

#include "common/types.h"

#include <array>
#include <memory>
#include <span>

namespace Arcade::JVS {

// Physical serial framing used between the Cyber Lead I/O C77 and the
// separate LED-board C77.
class NamcoCyberLeadLEDLink
{
public:
  static constexpr u8 DEFAULT_ADDRESS = UINT8_C(0x01);
  static constexpr u32 MAX_COMMAND_SIZE = 80;
  static constexpr u32 MAX_LOGICAL_FRAME_SIZE = MAX_COMMAND_SIZE + 3;
  static constexpr u32 MAX_WIRE_FRAME_SIZE = 1 + (MAX_LOGICAL_FRAME_SIZE * 2);

  struct Frame
  {
    // Unescaped frame excluding the E0 sync byte:
    //   destination, length, command bytes..., checksum
    std::array<u8, MAX_LOGICAL_FRAME_SIZE> logical{};
    u32 logical_size = 0;

    // Physical SCI1 byte stream including E0 sync and D0 escaping.
    std::array<u8, MAX_WIRE_FRAME_SIZE> wire{};
    u32 wire_size = 0;

    u8 checksum = 0;
    u64 generation = 0;
    bool valid = false;
  };

  void Reset();
  void SetAddress(u8 address) { m_address = address; }
  u8 GetAddress() const { return m_address; }

  bool QueueCommand(std::span<const u8> command);
  const Frame& GetLastFrame() const { return m_last_frame; }

private:
  static bool AppendEscapedByte(Frame& frame, u8 value);

  u8 m_address = DEFAULT_ADDRESS;
  Frame m_last_frame{};
};

// Firmware-backed Cyber Lead LED PCB (8699014500). The physical cabinet uses
// a second Namco C77 running cl1-leda.ic5. This device owns that CPU, its
// display/controller memory and the SCI1 endpoint connected to the I/O C77.
class NamcoCyberLeadLEDDevice
{
public:
  static constexpr u32 CLOCK_HZ = 14745600;
  static constexpr u32 FIRMWARE_SIZE = 0x40000;
  static constexpr u32 DISPLAY_RAM_SIZE = 0x2000;
  static constexpr u32 DISPLAY_CONTROL_SIZE = 0x10;
  static constexpr u32 SCROLL_SIZE = 2;
  static constexpr u32 FRAME_WIDTH = 96;
  static constexpr u32 FRAME_HEIGHT = 16;
  static constexpr u32 FRAME_PIXELS = FRAME_WIDTH * FRAME_HEIGHT;

  struct FrameState
  {
    // Physical cabinet orientation, including the Cyber Lead panel's ROT180.
    // Each element is the native 2-bit intensity value 0..3.
    std::array<u8, FRAME_PIXELS> pixels{};
    std::array<u32, 4> intensity_counts{};
    u64 generation = 0;
    u16 start_address = 0;
    u32 scroll_x = 0;
    u32 scroll_y = 0;
    bool valid = false;
  };

  struct Stats
  {
    u64 queued_frames = 0;
    u64 queued_wire_bytes = 0;
    u64 received_wire_bytes = 0;
    u64 transmitted_wire_bytes = 0;
    u64 display_ram_writes = 0;
    u64 display_control_writes = 0;
    u64 scroll_writes = 0;
    u64 timer_interrupts = 0;
    u64 vblank_interrupts = 0;
    u64 sci_rx_interrupts = 0;
    u64 frame_refreshes = 0;
    u64 frame_changes = 0;
    u64 cpu_steps = 0;
    u32 cpu_fault_code = 0;
    u32 cpu_fault_line = 0;
    u32 cpu_fault_pc = 0;
  };

  NamcoCyberLeadLEDDevice();
  ~NamcoCyberLeadLEDDevice();

  NamcoCyberLeadLEDDevice(NamcoCyberLeadLEDDevice&&) noexcept;
  NamcoCyberLeadLEDDevice& operator=(NamcoCyberLeadLEDDevice&&) noexcept;
  NamcoCyberLeadLEDDevice(const NamcoCyberLeadLEDDevice&) = delete;
  NamcoCyberLeadLEDDevice& operator=(const NamcoCyberLeadLEDDevice&) = delete;

  bool SetFirmware(std::span<const u8> firmware);
  bool HasFirmware() const;
  void Reset();

  // Queues the already-framed E0/D0 physical byte stream generated by the I/O
  // C77 model. Missing firmware is intentionally non-fatal: the game remains
  // playable with the cabinet display absent.
  bool QueueWireBytes(std::span<const u8> wire);

  // Advance from a source clock domain while preserving the exact fractional
  // relationship to the LED C77's 14.7456 MHz clock.
  void Advance(u32 source_clocks, u32 source_clock_hz);

  const Stats& GetStats() const;
  const FrameState& GetFrameState() const;
  std::span<const u8> GetDisplayRAM() const;
  std::span<const u8> GetDisplayControl() const;
  std::span<const u8> GetScroll() const;

private:
  struct Impl;
  std::unique_ptr<Impl> m_impl;
};

} // namespace Arcade::JVS