// SPDX-FileCopyrightText: 2019-2024 Connor McLaughlin <stenzek@gmail.com>
// SPDX-FileCopyrightText: 2026 StillJC
// SPDX-License-Identifier: GPL-3.0-only
//
// Modified for ArcadeDuck by StillJC, 2026.

#include "postprocessing_shader_fx.h"
#include "image.h"
#include "input_manager.h"
#include "shadergen.h"

// TODO: Remove me
#include "core/host.h"
#include "core/settings.h"

#include "common/assert.h"
#include "common/bitutils.h"
#include "common/error.h"
#include "common/file_system.h"
#include "common/log.h"
#include "common/path.h"
#include "common/progress_callback.h"
#include "common/string_util.h"

#include "effect_codegen.hpp"
#include "effect_module.hpp"
#include "effect_parser.hpp"
#include "effect_preprocessor.hpp"

#include "fmt/format.h"

#include <bitset>
#include <cctype>
#include <cmath>
#include <cstring>
#include <sstream>

Log_SetChannel(ReShadeFXShader);

static constexpr s32 DEFAULT_BUFFER_WIDTH = 3840;
static constexpr s32 DEFAULT_BUFFER_HEIGHT = 2160;

static RenderAPI GetRenderAPI()
{
  return g_gpu_device ? g_gpu_device->GetRenderAPI() : RenderAPI::D3D11;
}

static bool PreprocessorFileExistsCallback(const std::string& path)
{
  // ReShadeFX constructs include candidates with std::filesystem, so use its
  // native filesystem path handling first for user/package shaders.
  if (reshadefx::preprocessor::stdfs_file_exists_callback(path))
    return true;

  // Bundled ArcadeDuck includes are resource-relative rather than disk files.
  return !Path::IsAbsolute(path) && Host::ResourceFileExists(path.c_str(), true);
}

static bool PreprocessorReadFileCallback(const std::string& path, std::string& data)
{
  // Match ReShadeFX's own default filesystem reader for paths generated by its
  // preprocessor. Fall back to ArcadeDuck resources only for relative paths.
  if (reshadefx::preprocessor::stdfs_read_file_callback(path, data))
    return true;

  if (Path::IsAbsolute(path))
    return false;

  std::optional<std::string> rdata = Host::ReadResourceFileToString(path.c_str(), true);
  if (!rdata.has_value())
    return false;

  data = std::move(rdata.value());
  return true;
}
static std::unique_ptr<reshadefx::codegen> CreateRFXCodegen()
{
  const bool debug_info = g_gpu_device ? g_gpu_device->IsDebugDevice() : false;
  const bool uniforms_to_spec_constants = false;
  const RenderAPI rapi = GetRenderAPI();

  switch (rapi)
  {
    case RenderAPI::None:
    case RenderAPI::D3D11:
    case RenderAPI::D3D12:
      return std::unique_ptr<reshadefx::codegen>(
        reshadefx::create_codegen_hlsl(50, debug_info, uniforms_to_spec_constants));

    case RenderAPI::Vulkan:
    case RenderAPI::Metal:
      return std::unique_ptr<reshadefx::codegen>(reshadefx::create_codegen_glsl(
        true, debug_info, uniforms_to_spec_constants, false, (rapi == RenderAPI::Vulkan)));

    case RenderAPI::OpenGL:
    case RenderAPI::OpenGLES:
    default:
      return std::unique_ptr<reshadefx::codegen>(
        reshadefx::create_codegen_glsl(false, debug_info, uniforms_to_spec_constants, false, true));
  }
}

static GPUTexture::Format MapTextureFormat(reshadefx::texture_format format)
{
  switch (format)
  {
    case reshadefx::texture_format::r8:
      return GPUTexture::Format::R8;
    case reshadefx::texture_format::r16:
      return GPUTexture::Format::R16;
    case reshadefx::texture_format::r16f:
      return GPUTexture::Format::R16F;
    case reshadefx::texture_format::r32i:
      return GPUTexture::Format::R32I;
    case reshadefx::texture_format::r32u:
      return GPUTexture::Format::R32U;
    case reshadefx::texture_format::r32f:
      return GPUTexture::Format::R32F;
    case reshadefx::texture_format::rg8:
      return GPUTexture::Format::RG8;
    case reshadefx::texture_format::rg16:
      return GPUTexture::Format::RG16;
    case reshadefx::texture_format::rg16f:
      return GPUTexture::Format::RG16F;
    case reshadefx::texture_format::rg32f:
      return GPUTexture::Format::RG32F;
    case reshadefx::texture_format::rgba8:
      return GPUTexture::Format::RGBA8;
    case reshadefx::texture_format::rgba16:
      return GPUTexture::Format::RGBA16;
    case reshadefx::texture_format::rgba16f:
      return GPUTexture::Format::RGBA16F;
    case reshadefx::texture_format::rgba32f:
      return GPUTexture::Format::RGBA32F;
    case reshadefx::texture_format::rgb10a2:
      return GPUTexture::Format::RGB10A2;

    case reshadefx::texture_format::unknown:
    case reshadefx::texture_format::rgba32u:
    case reshadefx::texture_format::rgba32i:
    case reshadefx::texture_format::rg11b10f:
    default:
      return GPUTexture::Format::Unknown;
  }
}

static GPUSampler::Config MapSampler(const reshadefx::sampler& si)
{
  GPUSampler::Config config = GPUSampler::GetNearestConfig();

  switch (si.filter)
  {
    case reshadefx::filter_mode::min_mag_mip_point:
      config.min_filter = GPUSampler::Filter::Nearest;
      config.mag_filter = GPUSampler::Filter::Nearest;
      config.mip_filter = GPUSampler::Filter::Nearest;
      break;

    case reshadefx::filter_mode::min_mag_point_mip_linear:
      config.min_filter = GPUSampler::Filter::Nearest;
      config.mag_filter = GPUSampler::Filter::Nearest;
      config.mip_filter = GPUSampler::Filter::Linear;
      break;

    case reshadefx::filter_mode::min_point_mag_linear_mip_point:
      config.min_filter = GPUSampler::Filter::Linear;
      config.mag_filter = GPUSampler::Filter::Linear;
      config.mip_filter = GPUSampler::Filter::Nearest;
      break;

    case reshadefx::filter_mode::min_point_mag_mip_linear:
      config.min_filter = GPUSampler::Filter::Nearest;
      config.mag_filter = GPUSampler::Filter::Linear;
      config.mip_filter = GPUSampler::Filter::Linear;
      break;

    case reshadefx::filter_mode::min_linear_mag_mip_point:
      config.min_filter = GPUSampler::Filter::Linear;
      config.mag_filter = GPUSampler::Filter::Nearest;
      config.mip_filter = GPUSampler::Filter::Nearest;
      break;

    case reshadefx::filter_mode::min_linear_mag_point_mip_linear:
      config.min_filter = GPUSampler::Filter::Linear;
      config.mag_filter = GPUSampler::Filter::Nearest;
      config.mip_filter = GPUSampler::Filter::Linear;
      break;

    case reshadefx::filter_mode::min_mag_linear_mip_point:
      config.min_filter = GPUSampler::Filter::Linear;
      config.mag_filter = GPUSampler::Filter::Linear;
      config.mip_filter = GPUSampler::Filter::Nearest;
      break;

    case reshadefx::filter_mode::min_mag_mip_linear:
      config.min_filter = GPUSampler::Filter::Linear;
      config.mag_filter = GPUSampler::Filter::Linear;
      config.mip_filter = GPUSampler::Filter::Linear;
      break;

    default:
      break;
  }

  static constexpr auto map_address_mode = [](const reshadefx::texture_address_mode m) {
    switch (m)
    {
      case reshadefx::texture_address_mode::wrap:
        return GPUSampler::AddressMode::Repeat;
      case reshadefx::texture_address_mode::mirror:
        return GPUSampler::AddressMode::MirrorRepeat;
      case reshadefx::texture_address_mode::clamp:
        return GPUSampler::AddressMode::ClampToEdge;
      case reshadefx::texture_address_mode::border:
      default:
        return GPUSampler::AddressMode::ClampToBorder;
    }
  };

  config.address_u = map_address_mode(si.address_u);
  config.address_v = map_address_mode(si.address_v);
  config.address_w = map_address_mode(si.address_w);

  return config;
}

static GPUPipeline::BlendState MapBlendState(const reshadefx::pass& pass)
{
  // ReShadeFX enum values are stable wire-style values. Keep the translation
  // local and bounds-checked rather than mirroring the parser's switch layout.
  static constexpr std::array<GPUPipeline::BlendOp, 5> BLEND_OPERATIONS = {
    GPUPipeline::BlendOp::Add,
    GPUPipeline::BlendOp::Subtract,
    GPUPipeline::BlendOp::ReverseSubtract,
    GPUPipeline::BlendOp::Min,
    GPUPipeline::BlendOp::Max,
  };

  static constexpr std::array<GPUPipeline::BlendFunc, 10> BLEND_FACTORS = {
    GPUPipeline::BlendFunc::Zero,
    GPUPipeline::BlendFunc::One,
    GPUPipeline::BlendFunc::SrcColor,
    GPUPipeline::BlendFunc::InvSrcColor,
    GPUPipeline::BlendFunc::DstColor,
    GPUPipeline::BlendFunc::InvDstColor,
    GPUPipeline::BlendFunc::SrcAlpha,
    GPUPipeline::BlendFunc::InvSrcAlpha,
    GPUPipeline::BlendFunc::DstAlpha,
    GPUPipeline::BlendFunc::InvDstAlpha,
  };

  const auto decode_operation = [](reshadefx::blend_op value) {
    const u32 encoded = static_cast<u32>(value);
    return (encoded >= 1 && encoded <= BLEND_OPERATIONS.size()) ?
             BLEND_OPERATIONS[encoded - 1] :
             GPUPipeline::BlendOp::Max;
  };

  const auto decode_factor = [](reshadefx::blend_factor value) {
    const u32 encoded = static_cast<u32>(value);
    return (encoded < BLEND_FACTORS.size()) ? BLEND_FACTORS[encoded] : GPUPipeline::BlendFunc::InvDstAlpha;
  };

  constexpr size_t RT = 0;

  GPUPipeline::BlendState state = GPUPipeline::BlendState::GetNoBlendingState();
  state.enable = pass.blend_enable[RT];
  state.blend_op = decode_operation(pass.color_blend_op[RT]);
  state.src_blend = decode_factor(pass.source_color_blend_factor[RT]);
  state.dst_blend = decode_factor(pass.dest_color_blend_factor[RT]);
  state.alpha_blend_op = decode_operation(pass.alpha_blend_op[RT]);
  state.src_alpha_blend = decode_factor(pass.source_alpha_blend_factor[RT]);
  state.dst_alpha_blend = decode_factor(pass.dest_alpha_blend_factor[RT]);
  state.write_mask = pass.render_target_write_mask[RT];
  return state;
}

static GPUPipeline::Primitive MapPrimitive(reshadefx::primitive_topology topology)
{
  switch (topology)
  {
    case reshadefx::primitive_topology::point_list:
      return GPUPipeline::Primitive::Points;
    case reshadefx::primitive_topology::line_list:
      return GPUPipeline::Primitive::Lines;
    case reshadefx::primitive_topology::line_strip:
      Panic("Unhandled line strip");
    case reshadefx::primitive_topology::triangle_list:
      return GPUPipeline::Primitive::Triangles;
    case reshadefx::primitive_topology::triangle_strip:
    default:
      return GPUPipeline::Primitive::TriangleStrips;
  }
}

PostProcessing::ReShadeFXShader::ReShadeFXShader() = default;

PostProcessing::ReShadeFXShader::~ReShadeFXShader()
{
  for (Texture& tex : m_textures)
    g_gpu_device->RecycleTexture(std::move(tex.texture));
}

void PostProcessing::ReShadeFXShader::SetAdditionalIncludePath(std::string path)
{
  m_additional_include_path = std::move(path);
}

bool PostProcessing::ReShadeFXShader::LoadFromFile(std::string name, std::string filename, bool only_config,
                                                   Error* error)
{
  std::optional<std::string> data = FileSystem::ReadFileToString(filename.c_str(), error);
  if (!data.has_value())
  {
    ERROR_LOG("Failed to read '{}'.", filename);
    return false;
  }

  return LoadFromString(std::move(name), std::move(filename), std::move(data.value()), only_config, error);
}

bool PostProcessing::ReShadeFXShader::LoadFromString(std::string name, std::string filename, std::string code,
                                                     bool only_config, Error* error)
{
  DebugAssert(only_config || g_gpu_device);

  m_name = std::move(name);
  m_filename = std::move(filename);

  // ReShade's preprocessor expects this.
  if (code.empty() || code.back() != '\n')
    code.push_back('\n');

  reshadefx::effect_module temp_module;
  if (!CreateModule(only_config ? DEFAULT_BUFFER_WIDTH : g_gpu_device->GetWindowWidth(),
                    only_config ? DEFAULT_BUFFER_HEIGHT : g_gpu_device->GetWindowHeight(), &temp_module, nullptr,
                    std::move(code), error))
  {
    return false;
  }

  if (!CreateOptions(temp_module, error))
    return false;

  bool has_passes = false;
  for (const reshadefx::technique& tech : temp_module.techniques)
  {
    for (const reshadefx::pass& pi : tech.passes)
    {
      has_passes = true;

      if (!pi.cs_entry_point.empty())
      {
        Error::SetString(error, fmt::format("Compute pass '{}' is not supported by ArcadeDuck post-processing.", pi.name));
        return false;
      }
      if (!pi.storage_bindings.empty())
      {
        Error::SetString(error,
                         fmt::format("Storage/UAV bindings in pass '{}' are not supported by ArcadeDuck post-processing.",
                                     pi.name));
        return false;
      }

      u32 num_render_targets = 0;
      for (const std::string& rtname : pi.render_target_names)
      {
        if (rtname.empty())
          break;
        num_render_targets++;
      }
      if (num_render_targets > GPUDevice::MAX_RENDER_TARGETS)
      {
        Error::SetString(error,
                         fmt::format("Too many render targets ({}) in pass '{}', only {} are supported.",
                                     num_render_targets, pi.name, GPUDevice::MAX_RENDER_TARGETS));
        return false;
      }

      for (const reshadefx::texture_binding& binding : pi.texture_bindings)
      {
        if (binding.entry_point_binding >= GPUDevice::MAX_TEXTURE_SAMPLERS)
        {
          Error::SetString(error,
                           fmt::format("Texture binding {} in pass '{}' exceeds ArcadeDuck's {} texture slots.",
                                       binding.entry_point_binding, pi.name, GPUDevice::MAX_TEXTURE_SAMPLERS));
          return false;
        }
      }
      for (const reshadefx::sampler_binding& binding : pi.sampler_bindings)
      {
        if (binding.entry_point_binding >= GPUDevice::MAX_TEXTURE_SAMPLERS)
        {
          Error::SetString(error,
                           fmt::format("Sampler binding {} in pass '{}' exceeds ArcadeDuck's {} sampler slots.",
                                       binding.entry_point_binding, pi.name, GPUDevice::MAX_TEXTURE_SAMPLERS));
          return false;
        }
      }
    }
  }

  if (!has_passes)
  {
    Error::SetString(error, "No passes defined in file.");
    return false;
  }

  // Might go invalid when creating pipelines.
  m_valid = true;
  return true;
}

bool PostProcessing::ReShadeFXShader::IsValid() const
{
  return m_valid;
}

bool PostProcessing::ReShadeFXShader::WantsDepthBuffer() const
{
  return m_wants_depth_buffer;
}

bool PostProcessing::ReShadeFXShader::CreateModule(s32 buffer_width, s32 buffer_height,
                                                   reshadefx::effect_module* mod,
                                                   std::unique_ptr<reshadefx::codegen>* out_codegen, std::string code,
                                                   Error* error)
{
  reshadefx::preprocessor pp;
  pp.set_include_callbacks(PreprocessorFileExistsCallback, PreprocessorReadFileCallback);

  if (Path::IsAbsolute(m_filename))
  {
    // We're a real file, so include that directory.
    pp.add_include_path(std::string(Path::GetDirectory(m_filename)));
  }
  else
  {
    // We're a resource, include the resource subdirectory, if there is one.
    if (std::string_view resdir = Path::GetDirectory(m_filename); !resdir.empty())
      pp.add_include_path(std::string(resdir));
  }

  if (!m_additional_include_path.empty())
    pp.add_include_path(m_additional_include_path);

  // Root of the user directory, and resources.
  pp.add_include_path(Path::Combine(EmuFolders::Shaders, "reshade" FS_OSPATH_SEPARATOR_STR "Shaders"));
  pp.add_include_path("shaders/reshade/Shaders");

  // Keep the runtime compatibility level conservative. This modernization updates
  // the ReShadeFX compiler/parser, but ArcadeDuck does not implement the full newer
  // ReShade runtime API yet.
  pp.add_macro_definition("__RESHADE__", "50901");
  pp.add_macro_definition("BUFFER_WIDTH", StringUtil::ToChars(buffer_width));
  pp.add_macro_definition("BUFFER_HEIGHT", StringUtil::ToChars(buffer_height));
  pp.add_macro_definition("BUFFER_RCP_WIDTH", StringUtil::ToChars(1.0f / static_cast<float>(buffer_width)));
  pp.add_macro_definition("BUFFER_RCP_HEIGHT", StringUtil::ToChars(1.0f / static_cast<float>(buffer_height)));
  pp.add_macro_definition("BUFFER_COLOR_BIT_DEPTH", "32");
  pp.add_macro_definition("RESHADE_DEPTH_INPUT_IS_UPSIDE_DOWN", "0");
  pp.add_macro_definition("RESHADE_DEPTH_INPUT_IS_LOGARITHMIC", "0");
  pp.add_macro_definition("RESHADE_DEPTH_LINEARIZATION_FAR_PLANE", "1000.0");
  pp.add_macro_definition("RESHADE_DEPTH_INPUT_IS_REVERSED", "0");

  switch (GetRenderAPI())
  {
    case RenderAPI::D3D11:
    case RenderAPI::D3D12:
      pp.add_macro_definition("__RENDERER__", "0x0B000");
      break;

    case RenderAPI::OpenGL:
    case RenderAPI::OpenGLES:
    case RenderAPI::Vulkan:
    case RenderAPI::Metal:
      pp.add_macro_definition("__RENDERER__", "0x14300");
      break;

    default:
      UnreachableCode();
      break;
  }

  if (!pp.append_string(std::move(code), m_filename))
  {
    Error::SetString(error, fmt::format("Failed to preprocess:\n{}", pp.errors()));
    return false;
  }

  std::unique_ptr<reshadefx::codegen> cg = CreateRFXCodegen();
  if (!cg)
  {
    Error::SetString(error, "Failed to create ReShadeFX code generator.");
    return false;
  }

  reshadefx::parser parser;
  if (!parser.parse(pp.output(), cg.get()))
  {
    Error::SetString(error, fmt::format("Failed to parse:\n{}", parser.errors()));
    return false;
  }

  // The modern code generator owns the module while shader entry points are assembled.
  // Copy it out for metadata/runtime setup and optionally return the live generator.
  *mod = cg->module();
  if (out_codegen)
    *out_codegen = std::move(cg);

  return true;
}

static bool HasAnnotationWithName(const reshadefx::uniform& uniform, const std::string_view annotation_name)
{
  for (const reshadefx::annotation& an : uniform.annotations)
  {
    if (an.name == annotation_name)
      return true;
  }

  return false;
}

static std::string_view GetStringAnnotationValue(const std::vector<reshadefx::annotation>& annotations,
                                                 const std::string_view annotation_name,
                                                 const std::string_view default_value)
{
  for (const reshadefx::annotation& an : annotations)
  {
    if (an.name != annotation_name)
      continue;

    if (an.type.base != reshadefx::type::t_string)
      continue;

    return an.value.string_data;
  }

  return default_value;
}

static bool IsBlankReShadeUILabel(std::string_view value)
{
  for (const char ch : value)
  {
    if (!std::isspace(static_cast<unsigned char>(ch)))
      return false;
  }

  return true;
}

static bool IsReShadeInformationalUniform(const reshadefx::uniform& uniform)
{
  const std::string_view ui_type = GetStringAnnotationValue(uniform.annotations, "ui_type", std::string_view());
  if (ui_type != "radio" && ui_type != "combo")
    return false;

  const std::string_view ui_text = GetStringAnnotationValue(uniform.annotations, "ui_text", std::string_view());
  if (ui_text.empty())
    return false;

  const std::string_view ui_label = GetStringAnnotationValue(uniform.annotations, "ui_label", std::string_view());
  if (!IsBlankReShadeUILabel(ui_label))
    return false;

  // A real radio/combo has selectable items. ReShade help/version blocks use
  // the widget annotation only as a vehicle for ui_text and have no ui_items.
  const std::string_view ui_items = GetStringAnnotationValue(uniform.annotations, "ui_items", std::string_view());
  return ui_items.empty();
}
static bool GetBooleanAnnotationValue(const std::vector<reshadefx::annotation>& annotations,
                                      const std::string_view annotation_name, bool default_value)
{
  for (const reshadefx::annotation& an : annotations)
  {
    if (an.name != annotation_name)
      continue;

    if (an.type.base != reshadefx::type::t_bool)
      continue;

    return (an.value.as_int[0] != 0);
  }

  return default_value;
}

static PostProcessing::ShaderOption::ValueVector
GetVectorAnnotationValue(const reshadefx::uniform& uniform, const std::string_view annotation_name,
                         const PostProcessing::ShaderOption::ValueVector& default_value)
{
  PostProcessing::ShaderOption::ValueVector vv = default_value;
  for (const reshadefx::annotation& an : uniform.annotations)
  {
    if (an.name != annotation_name)
      continue;

    const u32 components = std::min<u32>(an.type.components(), PostProcessing::ShaderOption::MAX_VECTOR_COMPONENTS);

    if (an.type.base == uniform.type.base || (an.type.is_integral() && uniform.type.is_integral())) // int<->uint
    {
      if (components > 0)
        std::memcpy(&vv[0].float_value, &an.value.as_float[0], sizeof(float) * components);

      break;
    }
    else if (an.type.base == reshadefx::type::t_string)
    {
      // Convert from string.
      if (uniform.type.base == reshadefx::type::t_float)
      {
        if (an.value.string_data == "BUFFER_WIDTH")
          vv[0].float_value = DEFAULT_BUFFER_WIDTH;
        else if (an.value.string_data == "BUFFER_HEIGHT")
          vv[0].float_value = DEFAULT_BUFFER_HEIGHT;
        else
          vv[0].float_value = StringUtil::FromChars<float>(an.value.string_data).value_or(1000.0f);
      }
      else if (uniform.type.base == reshadefx::type::t_int)
      {
        if (an.value.string_data == "BUFFER_WIDTH")
          vv[0].int_value = DEFAULT_BUFFER_WIDTH;
        else if (an.value.string_data == "BUFFER_HEIGHT")
          vv[0].int_value = DEFAULT_BUFFER_HEIGHT;
        else
          vv[0].int_value = StringUtil::FromChars<s32>(an.value.string_data).value_or(1000);
      }
      else
      {
        ERROR_LOG("Unhandled string value for '{}' (annotation type: {}, uniform type {})", uniform.name,
                  an.type.description(), uniform.type.description());
      }

      break;
    }
    else if (an.type.base == reshadefx::type::t_int)
    {
      // Convert from int.
      if (uniform.type.base == reshadefx::type::t_float)
      {
        for (u32 i = 0; i < components; i++)
          vv[i].float_value = static_cast<float>(an.value.as_int[i]);
      }
      else if (uniform.type.base == reshadefx::type::t_bool)
      {
        for (u32 i = 0; i < components; i++)
          vv[i].int_value = (an.value.as_int[i] != 0) ? 1 : 0;
      }
    }
    else if (an.type.base == reshadefx::type::t_float)
    {
      // Convert from float.
      if (uniform.type.base == reshadefx::type::t_int)
      {
        for (u32 i = 0; i < components; i++)
          vv[i].int_value = static_cast<int>(an.value.as_float[i]);
      }
      else if (uniform.type.base == reshadefx::type::t_bool)
      {
        for (u32 i = 0; i < components; i++)
          vv[i].int_value = (an.value.as_float[i] != 0.0f) ? 1 : 0;
      }
    }

    break;
  }

  return vv;
}

bool PostProcessing::ReShadeFXShader::CreateOptions(const reshadefx::effect_module& mod, Error* error)
{
  for (const reshadefx::uniform& ui : mod.uniforms)
  {
    SourceOptionType so;
    if (!GetSourceOption(ui, &so, error))
      return false;
    if (so != SourceOptionType::None)
    {
      DEV_LOG("Add source based option {} at offset {} ({})", static_cast<u32>(so), ui.offset, ui.name);

      SourceOption sopt;
      sopt.source = so;
      sopt.offset = ui.offset;

      const ShaderOption::ValueVector min =
        GetVectorAnnotationValue(ui, "min", ShaderOption::MakeFloatVector(0, 0, 0, 0));
      const ShaderOption::ValueVector max =
        GetVectorAnnotationValue(ui, "max", ShaderOption::MakeFloatVector(1, 1, 1, 1));
      const ShaderOption::ValueVector smoothing =
        GetVectorAnnotationValue(ui, "smoothing", ShaderOption::MakeFloatVector(0));
      const ShaderOption::ValueVector step =
        GetVectorAnnotationValue(ui, "step", ShaderOption::MakeFloatVector(0, 1, 0, 0));

      sopt.min = min[0].float_value;
      sopt.max = max[0].float_value;
      sopt.smoothing = smoothing[0].float_value;
      std::memcpy(&sopt.step[0], &step[0].float_value, sizeof(sopt.value));
      std::memcpy(&sopt.value[0], &ui.initializer_value.as_float[0], sizeof(sopt.value));

      m_source_options.push_back(std::move(sopt));
      continue;
    }

    // Native ReShade shaders sometimes expose help/version text through a dummy
    // scalar uniform. It is not a shader setting and should not become a slider.
    if (IsReShadeInformationalUniform(ui))
      continue;

    ShaderOption opt;
    opt.name = ui.name;
    opt.category = GetStringAnnotationValue(ui.annotations, "ui_category", std::string_view());
    opt.tooltip = GetStringAnnotationValue(ui.annotations, "ui_tooltip", std::string_view());

    if (!GetBooleanAnnotationValue(ui.annotations, "hidden", false))
    {
      opt.ui_name = GetStringAnnotationValue(ui.annotations, "ui_label", std::string_view());
      if (opt.ui_name.empty())
        opt.ui_name = ui.name;
    }

    const std::string_view ui_type = GetStringAnnotationValue(ui.annotations, "ui_type", std::string_view());

    switch (ui.type.base)
    {
      case reshadefx::type::t_float:
        opt.type = ShaderOption::Type::Float;
        break;

      case reshadefx::type::t_int:
      case reshadefx::type::t_uint:
        opt.type = ShaderOption::Type::Int;
        break;

      case reshadefx::type::t_bool:
        opt.type = ShaderOption::Type::Bool;
        break;

      default:
        Error::SetString(error, fmt::format("Unhandled uniform type {} ({})", static_cast<u32>(ui.type.base), ui.name));
        return false;
    }

    opt.buffer_offset = ui.offset;
    opt.buffer_size = ui.size;
    opt.vector_size = ui.type.components();
    if (opt.vector_size == 0 || opt.vector_size > ShaderOption::MAX_VECTOR_COMPONENTS)
    {
      Error::SetString(error,
                       fmt::format("Unhandled vector size {} ({})", static_cast<u32>(ui.type.components()), ui.name));
      return false;
    }

    opt.min_value = GetVectorAnnotationValue(ui, "ui_min", opt.default_value);
    opt.max_value = GetVectorAnnotationValue(ui, "ui_max", opt.default_value);
    ShaderOption::ValueVector default_step = {};
    switch (opt.type)
    {
      case ShaderOption::Type::Float:
      {
        for (u32 i = 0; i < opt.vector_size; i++)
        {
          const float range = opt.max_value[i].float_value - opt.min_value[i].float_value;
          default_step[i].float_value = range / 100.0f;
        }
      }
      break;

      case ShaderOption::Type::Int:
      {
        for (u32 i = 0; i < opt.vector_size; i++)
        {
          const s32 range = opt.max_value[i].int_value - opt.min_value[i].int_value;
          default_step[i].int_value = std::max(range / 100, 1);
        }
      }
      break;

      default:
        break;
    }
    opt.step_value = GetVectorAnnotationValue(ui, "ui_step", default_step);

    // set a default maximum based on step if there isn't one
    if (!HasAnnotationWithName(ui, "ui_max") && HasAnnotationWithName(ui, "ui_step"))
    {
      for (u32 i = 0; i < opt.vector_size; i++)
      {
        switch (opt.type)
        {
          case ShaderOption::Type::Float:
            opt.max_value[i].float_value = opt.min_value[i].float_value + (opt.step_value[i].float_value * 100.0f);
            break;
          case ShaderOption::Type::Int:
            opt.max_value[i].int_value = opt.min_value[i].int_value + (opt.step_value[i].int_value * 100);
            break;
          default:
            break;
        }
      }
    }

    if (ui.has_initializer_value)
    {
      std::memcpy(&opt.default_value[0].float_value, &ui.initializer_value.as_float[0],
                  sizeof(float) * opt.vector_size);
    }
    else
    {
      opt.default_value = {};
    }

    // Assume default if user doesn't set it.
    opt.value = opt.default_value;

    if (!ui_type.empty() && opt.vector_size > 1)
    {
      WARNING_LOG("Uniform '{}' has UI type of '{}' but is vector not scalar ({}), ignoring", opt.name, ui_type,
                  opt.vector_size);
    }
    else if (!ui_type.empty())
    {
      if ((ui_type == "combo" || ui_type == "radio") && opt.type == ShaderOption::Type::Int)
      {
        const std::string_view ui_values = GetStringAnnotationValue(ui.annotations, "ui_items", std::string_view());

        size_t start_pos = 0;
        while (start_pos < ui_values.size())
        {
          size_t end_pos = start_pos;
          while (end_pos < ui_values.size() && ui_values[end_pos] != '\0')
            end_pos++;

          const size_t len = end_pos - start_pos;
          if (len > 0)
            opt.choice_options.emplace_back(ui_values.substr(start_pos, len));
          start_pos = end_pos + 1;
        }

        // update max if it hasn't been specified
        const size_t num_choices = opt.choice_options.size();
        if (num_choices > 0)
          opt.max_value[0].int_value = std::max(static_cast<s32>(num_choices - 1), opt.max_value[0].int_value);
      }
    }

    OptionList::iterator iter = std::find_if(m_options.begin(), m_options.end(),
                                             [&opt](const ShaderOption& it) { return it.category == opt.category; });
    if (iter != m_options.end())
    {
      // insert at the end of this category
      while (iter != m_options.end() && iter->category == opt.category)
        ++iter;
    }
    m_options.insert(iter, std::move(opt));
  }

  m_uniforms_size = mod.total_uniform_size;
  DEV_LOG("{}: {} options", m_filename, m_options.size());
  return true;
}

bool PostProcessing::ReShadeFXShader::GetSourceOption(const reshadefx::uniform& ui, SourceOptionType* si,
                                                      Error* error)
{
  // TODO: Rewrite these to a lookup table instead, this if chain is terrible.
  const std::string_view source = GetStringAnnotationValue(ui.annotations, "source", {});
  if (!source.empty())
  {
    if (source == "timer")
    {
      if (ui.type.base != reshadefx::type::t_float || ui.type.components() > 1)
      {
        Error::SetString(
          error, fmt::format("Unexpected type '{}' for timer source in uniform '{}'", ui.type.description(), ui.name));
        return false;
      }

      *si = SourceOptionType::Timer;
      return true;
    }
    else if (source == "framecount")
    {
      if ((!ui.type.is_integral() && !ui.type.is_floating_point()) || ui.type.components() > 1)
      {
        Error::SetString(
          error, fmt::format("Unexpected type '{}' for timer source in uniform '{}'", ui.type.description(), ui.name));
        return false;
      }

      *si = (ui.type.base == reshadefx::type::t_float) ? SourceOptionType::FrameCountF : SourceOptionType::FrameCount;
      return true;
    }
    else if (source == "frametime")
    {
      if (ui.type.base != reshadefx::type::t_float || ui.type.components() > 1)
      {
        Error::SetString(
          error, fmt::format("Unexpected type '{}' for timer source in uniform '{}'", ui.type.description(), ui.name));
        return false;
      }

      *si = SourceOptionType::FrameTime;
      return true;
    }
    else if (source == "pingpong")
    {
      if (!ui.type.is_floating_point() || ui.type.components() < 2)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' for pingpong source in uniform '{}'",
                                            ui.type.description(), ui.name));
        return false;
      }

      *si = SourceOptionType::PingPong;
      return true;
    }
    else if (source == "mousepoint")
    {
      if (!ui.type.is_floating_point() || ui.type.components() < 2)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' for mousepoint source in uniform '{}'",
                                            ui.type.description(), ui.name));
        return false;
      }

      *si = SourceOptionType::MousePoint;
      return true;
    }
    else if (source == "mousebutton")
    {
      WARNING_LOG("Ignoring mousebutton source in uniform '{}', not supported.", ui.name);
      *si = SourceOptionType::Zero;
      return true;
    }
    else if (source == "random")
    {
      if ((!ui.type.is_floating_point() && !ui.type.is_integral()) || ui.type.components() != 1)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' ({} components) for random source in uniform '{}'",
                                            ui.type.description(), ui.type.components(), ui.name));
        return false;
      }

      // TODO: This is missing min/max handling.
      *si = (ui.type.base == reshadefx::type::t_float) ? SourceOptionType::RandomF : SourceOptionType::Random;
      return true;
    }
    else if (source == "overlay_active")
    {
      *si = SourceOptionType::Zero;
      return true;
    }
    else if (source == "has_depth")
    {
      *si = SourceOptionType::HasDepth;
      return true;
    }
    else if (source == "bufferwidth")
    {
      *si = (ui.type.base == reshadefx::type::t_float) ? SourceOptionType::BufferWidthF : SourceOptionType::BufferWidth;
      return true;
    }
    else if (source == "bufferheight")
    {
      *si =
        (ui.type.base == reshadefx::type::t_float) ? SourceOptionType::BufferHeightF : SourceOptionType::BufferHeight;
      return true;
    }
    else if (source == "internalwidth")
    {
      *si =
        (ui.type.base == reshadefx::type::t_float) ? SourceOptionType::InternalWidthF : SourceOptionType::InternalWidth;
      return true;
    }
    else if (source == "internalheight")
    {
      *si = (ui.type.base == reshadefx::type::t_float) ? SourceOptionType::InternalHeightF :
                                                         SourceOptionType::InternalHeight;
      return true;
    }
    else if (source == "nativewidth")
    {
      *si = (ui.type.base == reshadefx::type::t_float) ? SourceOptionType::NativeWidthF : SourceOptionType::NativeWidth;
      return true;
    }
    else if (source == "nativeheight")
    {
      *si =
        (ui.type.base == reshadefx::type::t_float) ? SourceOptionType::NativeHeightF : SourceOptionType::NativeHeight;
      return true;
    }
    else if (source == "upscale_multiplier")
    {
      if (!ui.type.is_floating_point() || ui.type.components() != 1)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' for {} source in uniform '{}'", ui.type.description(),
                                            source, ui.name));
        return false;
      }

      *si = SourceOptionType::UpscaleMultiplier;
      return true;
    }
    else if (source == "viewportx")
    {
      if (!ui.type.is_floating_point() || ui.type.components() != 1)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' for {} source in uniform '{}'", ui.type.description(),
                                            source, ui.name));
        return false;
      }

      *si = SourceOptionType::ViewportX;
      return true;
    }
    else if (source == "viewporty")
    {
      if (!ui.type.is_floating_point() || ui.type.components() != 1)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' for {} source in uniform '{}'", ui.type.description(),
                                            source, ui.name));
        return false;
      }

      *si = SourceOptionType::ViewportY;
      return true;
    }
    else if (source == "viewportwidth")
    {
      if (!ui.type.is_floating_point() || ui.type.components() != 1)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' for {} source in uniform '{}'", ui.type.description(),
                                            source, ui.name));
        return false;
      }

      *si = SourceOptionType::ViewportWidth;
      return true;
    }
    else if (source == "viewportheight")
    {
      if (!ui.type.is_floating_point() || ui.type.components() != 1)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' for {} source in uniform '{}'", ui.type.description(),
                                            source, ui.name));
        return false;
      }

      *si = SourceOptionType::ViewportHeight;
      return true;
    }
    else if (source == "viewportoffset")
    {
      if (!ui.type.is_floating_point() || ui.type.components() != 2)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' for {} source in uniform '{}'", ui.type.description(),
                                            source, ui.name));
        return false;
      }

      *si = SourceOptionType::ViewportOffset;
      return true;
    }
    else if (source == "viewportsize")
    {
      if (!ui.type.is_floating_point() || ui.type.components() != 2)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' for {} source in uniform '{}'", ui.type.description(),
                                            source, ui.name));
        return false;
      }

      *si = SourceOptionType::ViewportSize;
      return true;
    }
    else if (source == "internal_pixel_size")
    {
      if (!ui.type.is_floating_point() || ui.type.components() != 2)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' for {} source in uniform '{}'", ui.type.description(),
                                            source, ui.name));
        return false;
      }

      *si = SourceOptionType::InternalPixelSize;
      return true;
    }
    else if (source == "normalized_internal_pixel_size")
    {
      if (!ui.type.is_floating_point() || ui.type.components() != 2)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' for {} source in uniform '{}'", ui.type.description(),
                                            source, ui.name));
        return false;
      }

      *si = SourceOptionType::InternalNormPixelSize;
      return true;
    }
    else if (source == "native_pixel_size")
    {
      if (!ui.type.is_floating_point() || ui.type.components() != 2)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' for {} source in uniform '{}'", ui.type.description(),
                                            source, ui.name));
        return false;
      }

      *si = SourceOptionType::NativePixelSize;
      return true;
    }
    else if (source == "normalized_native_pixel_size")
    {
      if (!ui.type.is_floating_point() || ui.type.components() != 2)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' for {} source in uniform '{}'", ui.type.description(),
                                            source, ui.name));
        return false;
      }

      *si = SourceOptionType::NativeNormPixelSize;
      return true;
    }
    else if (source == "buffer_to_viewport_ratio")
    {
      if (!ui.type.is_floating_point() || ui.type.components() != 2)
      {
        Error::SetString(error, fmt::format("Unexpected type '{}' for {} source in uniform '{}'", ui.type.description(),
                                            source, ui.name));
        return false;
      }

      *si = SourceOptionType::BufferToViewportRatio;
      return true;
    }
    else
    {
      Error::SetString(error, fmt::format("Unknown source '{}' in uniform '{}'", source, ui.name));
      return false;
    }
  }

  if (ui.has_initializer_value)
  {
    if (ui.initializer_value.string_data == "BUFFER_WIDTH")
    {
      *si = (ui.type.base == reshadefx::type::t_float) ? SourceOptionType::BufferWidthF : SourceOptionType::BufferWidth;
      return true;
    }
    else if (ui.initializer_value.string_data == "BUFFER_HEIGHT")
    {
      *si =
        (ui.type.base == reshadefx::type::t_float) ? SourceOptionType::BufferHeightF : SourceOptionType::BufferHeight;
      return true;
    }
  }

  *si = SourceOptionType::None;
  return true;
}

bool PostProcessing::ReShadeFXShader::CreatePasses(GPUTexture::Format backbuffer_format,
                                                   const reshadefx::effect_module& mod, Error* error)
{
  u32 total_passes = 0;
  for (const reshadefx::technique& tech : mod.techniques)
    total_passes += static_cast<u32>(tech.passes.size());
  if (total_passes == 0)
  {
    Error::SetString(error, "No passes defined.");
    return false;
  }

  m_passes.reserve(total_passes);

  // Named render targets and source textures.
  for (const reshadefx::texture& ti : mod.textures)
  {
    Texture tex = {};

    if (!ti.semantic.empty())
    {
      DEV_LOG("Ignoring semantic {} texture {}", ti.semantic, ti.unique_name);
      continue;
    }

    if (ti.render_target)
    {
      tex.rt_scale = 1.0f;
      tex.format = (ti.format == reshadefx::texture_format::unknown) ? backbuffer_format : MapTextureFormat(ti.format);
      if (tex.format == GPUTexture::Format::Unknown)
      {
        Error::SetString(error,
                         fmt::format("Unsupported texture format {} for render target '{}'.",
                                     static_cast<u32>(ti.format), ti.unique_name));
        return false;
      }
      DEV_LOG("Creating render target '{}' {}", ti.unique_name, GPUTexture::GetFormatName(tex.format));
    }
    else
    {
      const std::string_view source = GetStringAnnotationValue(ti.annotations, "source", {});
      if (source.empty())
      {
        Error::SetString(error, fmt::format("Non-render target texture '{}' is missing source.", ti.unique_name));
        return false;
      }

      RGBA8Image image;
      if (const std::string image_path =
            Path::Combine(EmuFolders::Shaders, Path::Combine("reshade" FS_OSPATH_SEPARATOR_STR "Textures", source));
          !image.LoadFromFile(image_path.c_str()))
      {
        // Might be a base file/resource instead.
        const std::string resource_name = Path::Combine("shaders/reshade/Textures", source);
        if (std::optional<DynamicHeapArray<u8>> resdata = Host::ReadResourceFile(resource_name.c_str(), true);
            !resdata.has_value() || !image.LoadFromBuffer(resource_name.c_str(), resdata->data(), resdata->size()))
        {
          Error::SetString(error, fmt::format("Failed to load image '{}' (from '{}')", source, image_path).c_str());
          return false;
        }
      }

      tex.rt_scale = 0.0f;
      tex.format = GPUTexture::Format::RGBA8;
      tex.texture = g_gpu_device->FetchTexture(image.GetWidth(), image.GetHeight(), 1, 1, 1, GPUTexture::Type::Texture,
                                               GPUTexture::Format::RGBA8, image.GetPixels(), image.GetPitch());
      if (!tex.texture)
      {
        Error::SetString(
          error, fmt::format("Failed to create {}x{} texture ({})", image.GetWidth(), image.GetHeight(), source));
        return false;
      }

      DEV_LOG("Loaded {}x{} texture ({})", image.GetWidth(), image.GetHeight(), source);
    }

    tex.reshade_name = ti.unique_name;
    m_textures.push_back(std::move(tex));
  }

  const auto resolve_texture = [this, &mod, error](const reshadefx::sampler& si, const reshadefx::pass& pi,
                                                   TextureID input_color_id, TextureID* out_texture_id) -> bool {
    TextureID texture_id = static_cast<TextureID>(m_textures.size());
    for (const reshadefx::texture& ti : mod.textures)
    {
      if (ti.unique_name != si.texture_name)
        continue;

      if (ti.semantic == "COLOR")
      {
        texture_id = input_color_id;
      }
      else if (ti.semantic == "DEPTH")
      {
        texture_id = INPUT_DEPTH_TEXTURE;
        m_wants_depth_buffer = true;
      }
      else if (!ti.semantic.empty())
      {
        Error::SetString(error, fmt::format("Unknown semantic '{}' in texture '{}'.", ti.semantic, ti.name));
        return false;
      }
      else
      {
        for (u32 i = 0; i < static_cast<u32>(m_textures.size()); i++)
        {
          if (m_textures[i].reshade_name == si.texture_name)
          {
            texture_id = static_cast<TextureID>(i);
            break;
          }
        }
      }
      break;
    }

    if (texture_id == static_cast<TextureID>(m_textures.size()))
    {
      Error::SetString(error,
                       fmt::format("Unknown texture '{}' (sampler '{}') in pass '{}'.", si.texture_name, si.name,
                                   pi.name));
      return false;
    }

    *out_texture_id = texture_id;
    return true;
  };

  TextureID current_color_texture = INPUT_COLOR_TEXTURE;

  for (const reshadefx::technique& tech : mod.techniques)
  {
    for (const reshadefx::pass& pi : tech.passes)
    {
      if (!pi.cs_entry_point.empty())
      {
        Error::SetString(error, fmt::format("Compute pass '{}' is not supported by ArcadeDuck post-processing.", pi.name));
        return false;
      }
      if (!pi.storage_bindings.empty())
      {
        Error::SetString(error,
                         fmt::format("Storage/UAV bindings in pass '{}' are not supported by ArcadeDuck post-processing.",
                                     pi.name));
        return false;
      }

      const bool is_final = (&tech == &mod.techniques.back() && &pi == &tech.passes.back());
      const TextureID pass_input_color = current_color_texture;

      Pass pass = {};
      pass.num_vertices = pi.num_vertices;

      if (is_final)
      {
        pass.render_targets.push_back(OUTPUT_COLOR_TEXTURE);
      }
      else if (!pi.render_target_names[0].empty())
      {
        for (const std::string& rtname : pi.render_target_names)
        {
          if (rtname.empty())
            break;

          TextureID rt = static_cast<TextureID>(m_textures.size());
          for (u32 i = 0; i < static_cast<u32>(m_textures.size()); i++)
          {
            if (m_textures[i].reshade_name == rtname)
            {
              rt = static_cast<TextureID>(i);
              break;
            }
          }
          if (rt == static_cast<TextureID>(m_textures.size()))
          {
            Error::SetString(error,
                             fmt::format("Unknown texture '{}' used as render target in pass '{}'.", rtname, pi.name));
            return false;
          }

          pass.render_targets.push_back(rt);
        }
      }
      else
      {
        Texture new_rt = {};
        new_rt.rt_scale = 1.0f;
        new_rt.format = backbuffer_format;
        current_color_texture = static_cast<TextureID>(m_textures.size());
        pass.render_targets.push_back(current_color_texture);
        m_textures.push_back(std::move(new_rt));
      }

      const auto find_or_add_binding = [&pass](u32 slot) -> Binding& {
        for (Binding& existing : pass.bindings)
        {
          if (existing.slot == slot)
            return existing;
        }

        Binding binding = {};
        binding.slot = slot;
        binding.texture_id = INPUT_COLOR_TEXTURE;
        binding.has_texture = false;
        binding.sampler = nullptr;
        pass.bindings.push_back(binding);
        return pass.bindings.back();
      };

      for (const reshadefx::texture_binding& tb : pi.texture_bindings)
      {
        if (tb.index >= mod.samplers.size())
        {
          Error::SetString(error, fmt::format("Invalid texture binding in pass '{}'.", pi.name));
          return false;
        }

        const reshadefx::sampler& si = mod.samplers[tb.index];
        Binding& binding = find_or_add_binding(tb.entry_point_binding);
        if (!resolve_texture(si, pi, pass_input_color, &binding.texture_id))
          return false;
        binding.has_texture = true;

      }

      for (const reshadefx::sampler_binding& sb : pi.sampler_bindings)
      {
        if (sb.index >= mod.samplers.size())
        {
          Error::SetString(error, fmt::format("Invalid sampler binding in pass '{}'.", pi.name));
          return false;
        }

        const reshadefx::sampler& si = mod.samplers[sb.index];
        Binding& binding = find_or_add_binding(sb.entry_point_binding);
        binding.sampler = GetSampler(MapSampler(si));
        if (!binding.sampler)
        {
          Error::SetString(error, fmt::format("Failed to create sampler '{}' in pass '{}'.", si.name, pi.name));
          return false;
        }
      }

      for (const Binding& binding : pass.bindings)
      {
        if (binding.has_texture)
          DEV_LOG("Pass {} binding {} => texture {} sampler={}", pi.name, binding.slot, binding.texture_id,
                  binding.sampler != nullptr);
        else
          DEV_LOG("Pass {} binding {} => sampler-only", pi.name, binding.slot);
      }

#ifdef _DEBUG
      pass.name = pi.name;
#endif
      m_passes.push_back(std::move(pass));
    }
  }

  return true;
}

const char* PostProcessing::ReShadeFXShader::GetTextureNameForID(TextureID id) const
{
  if (id == INPUT_COLOR_TEXTURE)
    return "Input Color Texture / Backbuffer";
  else if (id == INPUT_DEPTH_TEXTURE)
    return "Input Depth Texture";
  else if (id == OUTPUT_COLOR_TEXTURE)
    return "Output Color Texture";
  else if (id < 0 || static_cast<size_t>(id) >= m_textures.size())
    return "UNKNOWN";
  else
    return m_textures[static_cast<size_t>(id)].reshade_name.c_str();
}

GPUTexture* PostProcessing::ReShadeFXShader::GetTextureByID(TextureID id, GPUTexture* input_color,
                                                            GPUTexture* input_depth, GPUTexture* final_target) const
{
  if (id < 0)
  {
    if (id == INPUT_COLOR_TEXTURE)
    {
      return input_color;
    }
    else if (id == INPUT_DEPTH_TEXTURE)
    {
      return input_depth ? input_depth : GetDummyTexture();
    }
    else if (id == OUTPUT_COLOR_TEXTURE)
    {
      return final_target;
    }
    else
    {
      Panic("Unexpected reserved texture ID");
      return nullptr;
    }
  }

  if (static_cast<size_t>(id) >= m_textures.size())
    Panic("Unexpected texture ID");

  return m_textures[static_cast<size_t>(id)].texture.get();
}

bool PostProcessing::ReShadeFXShader::CompilePipeline(GPUTexture::Format format, u32 width, u32 height,
                                                      ProgressCallback* progress)
{
  const RenderAPI api = g_gpu_device->GetRenderAPI();

  m_valid = false;
  m_textures.clear();
  m_passes.clear();
  m_wants_depth_buffer = false;

  std::string fxcode;
  if (!PreprocessorReadFileCallback(m_filename, fxcode))
  {
    ERROR_LOG("Failed to re-read shader for pipeline: '{}'", m_filename);
    return false;
  }

  // ReShade's preprocessor expects this.
  if (fxcode.empty() || fxcode.back() != '\n')
    fxcode.push_back('\n');

  Error error;
  reshadefx::effect_module mod;
  std::unique_ptr<reshadefx::codegen> codegen;
  if (!CreateModule(width, height, &mod, &codegen, std::move(fxcode), &error))
  {
    ERROR_LOG("Failed to create module for '{}': {}", m_name, error.GetDescription());
    return false;
  }

  DebugAssert(!mod.techniques.empty());

  if (!CreatePasses(format, mod, &error))
  {
    ERROR_LOG("Failed to create passes for '{}': {}", m_name, error.GetDescription());
    return false;
  }

  auto get_shader = [api, &codegen](const std::string& name, GPUShaderStage stage) {
    std::string real_code;
    std::string assembly;
    std::string assembly_errors;
    if (!codegen->assemble_code_for_entry_point(name, real_code, assembly, assembly_errors))
    {
      ERROR_LOG("Failed to assemble ReShadeFX function '{}': {}", name,
                assembly_errors.empty() ? "unknown code generation error" : assembly_errors);
      return std::unique_ptr<GPUShader>();
    }

    if (api == RenderAPI::Vulkan || api == RenderAPI::Metal)
    {
      // ArcadeDuck's MultiTextureAndUBO Vulkan-style pipeline layout uses set 0
      // for the uniform buffer and set 1 for combined image samplers.
      StringUtil::ReplaceAll(&real_code, "layout(std140, column_major, binding = 0) uniform _Globals",
                             "layout(std140, column_major, set = 0, binding = 0) uniform _Globals");

      size_t search_pos = 0;
      while ((search_pos = real_code.find("layout(binding = ", search_pos)) != std::string::npos)
      {
        real_code.insert(search_pos + 7, "set = 1, ");
        search_pos += 16;
      }
    }
#ifdef ENABLE_OPENGL
    else if (api == RenderAPI::OpenGL || api == RenderAPI::OpenGLES)
    {
      const size_t version_end = real_code.find('\n');
      if (version_end != std::string::npos && real_code.compare(0, 9, "#version ") == 0)
      {
        real_code = fmt::format("{}\n{}", ShaderGen::GetGLSLVersionString(api, ShaderGen::GetGLSLVersion(api)),
                                real_code.substr(version_end + 1));
      }

      if (api == RenderAPI::OpenGLES)
      {
        const size_t first_newline = real_code.find('\n');
        if (first_newline != std::string::npos)
        {
          real_code.insert(first_newline + 1,
                           "precision highp float;\nprecision highp int;\nprecision highp sampler2D;\n");
        }
      }
    }
#endif

    Error shader_error;
    const GPUShaderLanguage language = ShaderGen::GetShaderLanguageForAPI(api);
    const char* entry_point = (language == GPUShaderLanguage::HLSL) ? name.c_str() : "main";
    std::unique_ptr<GPUShader> shader =
      g_gpu_device->CreateShader(stage, language, real_code, &shader_error, entry_point);
    if (!shader)
      ERROR_LOG("Failed to compile function '{}': {}", name, shader_error.GetDescription());

    return shader;
  };

  GPUPipeline::GraphicsConfig plconfig;
  plconfig.layout = GPUPipeline::Layout::MultiTextureAndUBO;
  plconfig.primitive = GPUPipeline::Primitive::Triangles;
  plconfig.depth_format = GPUTexture::Format::Unknown;
  plconfig.rasterization = GPUPipeline::RasterizationState::GetNoCullState();
  plconfig.depth = GPUPipeline::DepthState::GetNoTestsState();
  plconfig.blend = GPUPipeline::BlendState::GetNoBlendingState();
  plconfig.samples = 1;
  plconfig.per_sample_shading = false;
  plconfig.render_pass_flags = GPUPipeline::NoRenderPassFlags;

  progress->PushState();

  size_t total_passes = 0;
  for (const reshadefx::technique& tech : mod.techniques)
    total_passes += tech.passes.size();
  progress->SetProgressRange(static_cast<u32>(total_passes));
  progress->SetProgressValue(0);

  u32 passnum = 0;
  for (const reshadefx::technique& tech : mod.techniques)
  {
    for (const reshadefx::pass& info : tech.passes)
    {
      DebugAssert(passnum < m_passes.size());
      Pass& pass = m_passes[passnum++];

      auto vs = get_shader(info.vs_entry_point, GPUShaderStage::Vertex);
      auto fs = get_shader(info.ps_entry_point, GPUShaderStage::Fragment);
      if (!vs || !fs)
      {
        progress->PopState();
        return false;
      }

      for (size_t i = 0; i < pass.render_targets.size(); i++)
      {
        plconfig.color_formats[i] =
          ((pass.render_targets[i] >= 0) ? m_textures[pass.render_targets[i]].format : format);
      }
      for (size_t i = pass.render_targets.size(); i < GPUDevice::MAX_RENDER_TARGETS; i++)
        plconfig.color_formats[i] = GPUTexture::Format::Unknown;
      plconfig.depth_format = GPUTexture::Format::Unknown;

      plconfig.blend = MapBlendState(info);
      plconfig.primitive = MapPrimitive(info.topology);
      plconfig.vertex_shader = vs.get();
      plconfig.fragment_shader = fs.get();
      plconfig.geometry_shader = nullptr;

      pass.pipeline = g_gpu_device->CreatePipeline(plconfig);
      if (!pass.pipeline)
      {
        ERROR_LOG("Failed to create pipeline for pass '{}'", info.name);
        progress->PopState();
        return false;
      }

      progress->SetProgressValue(passnum);
    }
  }

  progress->PopState();

  m_valid = true;
  return true;
}

bool PostProcessing::ReShadeFXShader::ResizeOutput(GPUTexture::Format format, u32 width, u32 height)
{
  m_valid = false;

  for (Texture& tex : m_textures)
  {
    if (tex.rt_scale == 0.0f)
      continue;

    g_gpu_device->RecycleTexture(std::move(tex.texture));

    const u32 t_width = std::max(static_cast<u32>(static_cast<float>(width) * tex.rt_scale), 1u);
    const u32 t_height = std::max(static_cast<u32>(static_cast<float>(height) * tex.rt_scale), 1u);
    tex.texture = g_gpu_device->FetchTexture(t_width, t_height, 1, 1, 1, GPUTexture::Type::RenderTarget, tex.format);
    if (!tex.texture)
    {
      ERROR_LOG("Failed to create {}x{} texture", t_width, t_height);
      return {};
    }
  }

  m_valid = true;
  return true;
}

bool PostProcessing::ReShadeFXShader::Apply(GPUTexture* input_color, GPUTexture* input_depth, GPUTexture* final_target,
                                            GSVector4i final_rect, s32 orig_width, s32 orig_height, s32 native_width,
                                            s32 native_height, u32 target_width, u32 target_height)
{
  GL_PUSH_FMT("PostProcessingShaderFX {}", m_name);

  m_frame_count++;

  // Reshade always draws at full size.
  g_gpu_device->SetViewportAndScissor(GSVector4i(0, 0, target_width, target_height));

  if (m_uniforms_size > 0)
  {
    GL_SCOPE_FMT("Uniforms: {} bytes", m_uniforms_size);

    u8* uniforms = static_cast<u8*>(g_gpu_device->MapUniformBuffer(m_uniforms_size));
    for (const ShaderOption& opt : m_options)
    {
      DebugAssert((opt.buffer_offset + opt.buffer_size) <= m_uniforms_size);
      std::memcpy(uniforms + opt.buffer_offset, &opt.value[0].float_value, opt.buffer_size);
    }
    for (const SourceOption& so : m_source_options)
    {
      u8* dst = uniforms + so.offset;
      switch (so.source)
      {
        case SourceOptionType::Zero:
        {
          const u32 value = 0;
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::HasDepth:
        {
          const u32 value = BoolToUInt32(input_depth != nullptr);
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::Timer:
        {
          const float value = static_cast<float>(PostProcessing::GetTimer().GetTimeMilliseconds());
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::FrameTime:
        {
          const float value = static_cast<float>(m_frame_timer.GetTimeMilliseconds());
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::FrameCount:
        {
          std::memcpy(dst, &m_frame_count, sizeof(m_frame_count));
        }
        break;

        case SourceOptionType::FrameCountF:
        {
          const float value = static_cast<float>(m_frame_count);
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::PingPong:
        {
          float increment = so.step[1] == 0 ?
                              so.step[0] :
                              (so.step[0] + std::fmod(static_cast<float>(std::rand()), so.step[1] - so.step[0] + 1));

          std::array<float, 2> value = {so.value[0].float_value, so.value[1].float_value};
          if (value[1] >= 0)
          {
            increment = std::max(increment - std::max(0.0f, so.smoothing - (so.max - value[0])), 0.05f);
            increment *= static_cast<float>(m_frame_timer.GetTimeMilliseconds() * 1e-9);

            if ((value[0] += increment) >= so.max)
            {
              value[0] = so.max;
              value[1] = -1;
            }
          }
          else
          {
            increment = std::max(increment - std::max(0.0f, so.smoothing - (value[0] - so.min)), 0.05f);
            increment *= static_cast<float>(m_frame_timer.GetTimeMilliseconds() * 1e-9);

            if ((value[0] -= increment) <= so.min)
            {
              value[0] = so.min;
              value[1] = +1;
            }
          }

          std::memcpy(dst, value.data(), sizeof(value));
        }
        break;

        case SourceOptionType::MousePoint:
        {
          const std::pair<float, float> mpos = InputManager::GetPointerAbsolutePosition(0);
          std::memcpy(dst, &mpos.first, sizeof(float));
          std::memcpy(dst + sizeof(float), &mpos.second, sizeof(float));
        }
        break;

        case SourceOptionType::Random:
        {
          const s32 rv = m_random() % 32767; // reshade uses rand(), which on some platforms has a 0x7fff maximum.
          std::memcpy(dst, &rv, sizeof(rv));
        }
        break;
        case SourceOptionType::RandomF:
        {
          const float rv = (m_random() - m_random.min()) / static_cast<float>(m_random.max() - m_random.min());
          std::memcpy(dst, &rv, sizeof(rv));
        }
        break;

        case SourceOptionType::BufferWidth:
        case SourceOptionType::BufferHeight:
        {
          const s32 value = (so.source == SourceOptionType::BufferWidth) ? static_cast<s32>(target_width) :
                                                                           static_cast<s32>(target_height);
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::BufferWidthF:
        case SourceOptionType::BufferHeightF:
        {
          const float value = (so.source == SourceOptionType::BufferWidthF) ? static_cast<float>(target_width) :
                                                                              static_cast<float>(target_height);
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::InternalWidth:
        case SourceOptionType::InternalHeight:
        {
          const s32 value = (so.source == SourceOptionType::InternalWidth) ? static_cast<s32>(orig_width) :
                                                                             static_cast<s32>(orig_height);
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::InternalWidthF:
        case SourceOptionType::InternalHeightF:
        {
          const float value = (so.source == SourceOptionType::InternalWidthF) ? static_cast<float>(orig_width) :
                                                                                static_cast<float>(orig_height);
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::NativeWidth:
        case SourceOptionType::NativeHeight:
        {
          const s32 value = (so.source == SourceOptionType::NativeWidth) ? static_cast<s32>(native_width) :
                                                                           static_cast<s32>(native_height);
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::NativeWidthF:
        case SourceOptionType::NativeHeightF:
        {
          const float value = (so.source == SourceOptionType::NativeWidthF) ? static_cast<float>(native_width) :
                                                                              static_cast<float>(native_height);
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::UpscaleMultiplier:
        {
          const float value = static_cast<float>(orig_width) / static_cast<float>(native_width);
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::ViewportX:
        {
          const float value = static_cast<float>(final_rect.left);
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::ViewportY:
        {
          const float value = static_cast<float>(final_rect.top);
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::ViewportWidth:
        {
          const float value = static_cast<float>(final_rect.width());
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::ViewportHeight:
        {
          const float value = static_cast<float>(final_rect.height());
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::ViewportOffset:
        {
          GSVector4::storel(dst, GSVector4(final_rect));
        }
        break;

        case SourceOptionType::ViewportSize:
        {
          const float value[2] = {static_cast<float>(final_rect.width()), static_cast<float>(final_rect.height())};
          std::memcpy(dst, &value, sizeof(value));
        }
        break;

        case SourceOptionType::InternalPixelSize:
        {
          const float value[2] = {static_cast<float>(final_rect.width()) / static_cast<float>(orig_width),
                                  static_cast<float>(final_rect.height()) / static_cast<float>(orig_height)};
          std::memcpy(dst, value, sizeof(value));
        }
        break;

        case SourceOptionType::InternalNormPixelSize:
        {
          const float value[2] = {(static_cast<float>(final_rect.width()) / static_cast<float>(orig_width)) /
                                    static_cast<float>(target_width),
                                  (static_cast<float>(final_rect.height()) / static_cast<float>(orig_height)) /
                                    static_cast<float>(target_height)};
          std::memcpy(dst, value, sizeof(value));
        }
        break;

        case SourceOptionType::NativePixelSize:
        {
          const float value[2] = {static_cast<float>(final_rect.width()) / static_cast<float>(native_width),
                                  static_cast<float>(final_rect.height()) / static_cast<float>(native_height)};
          std::memcpy(dst, value, sizeof(value));
        }
        break;

        case SourceOptionType::NativeNormPixelSize:
        {
          const float value[2] = {(static_cast<float>(final_rect.width()) / static_cast<float>(native_width)) /
                                    static_cast<float>(target_width),
                                  (static_cast<float>(final_rect.height()) / static_cast<float>(native_height)) /
                                    static_cast<float>(target_height)};
          std::memcpy(dst, value, sizeof(value));
        }
        break;

        case SourceOptionType::BufferToViewportRatio:
        {
          const float value[2] = {static_cast<float>(target_width) / static_cast<float>(final_rect.width()),
                                  static_cast<float>(target_height) / static_cast<float>(final_rect.height())};
          std::memcpy(dst, value, sizeof(value));
        }
        break;

        default:
          UnreachableCode();
          break;
      }
    }
    g_gpu_device->UnmapUniformBuffer(m_uniforms_size);
  }

  for (const Pass& pass : m_passes)
  {
    GL_SCOPE_FMT("Draw pass {}", pass.name.c_str());
    DebugAssert(!pass.render_targets.empty());

    // Sucks doing this twice, but we need to set the RT first (for DX11), and transition layouts (for VK).
    for (const Binding& binding : pass.bindings)
    {
      if (!binding.has_texture)
        continue;

      GPUTexture* const tex = GetTextureByID(binding.texture_id, input_color, input_depth, final_target);
      if (tex)
        tex->MakeReadyForSampling();
    }

    if (pass.render_targets.size() == 1 && pass.render_targets[0] == OUTPUT_COLOR_TEXTURE && !final_target)
    {
      // Special case: drawing to final buffer.
      if (!g_gpu_device->BeginPresent(false))
      {
        GL_POP();
        return false;
      }
    }
    else
    {
      std::array<GPUTexture*, GPUDevice::MAX_RENDER_TARGETS> render_targets;
      for (size_t i = 0; i < pass.render_targets.size(); i++)
      {
        GL_INS_FMT("Render Target {}: ID {} [{}]", i, pass.render_targets[i],
                   GetTextureNameForID(pass.render_targets[i]));
        render_targets[i] = GetTextureByID(pass.render_targets[i], input_color, input_depth, final_target);
        DebugAssert(render_targets[i]);
      }

      g_gpu_device->SetRenderTargets(render_targets.data(), static_cast<u32>(pass.render_targets.size()), nullptr);
    }

    g_gpu_device->SetPipeline(pass.pipeline.get());

    // ReShadeFX keeps texture and sampler registers in separate binding spaces.
    // D3D11 may therefore use tN and sM with different indices. Set each numeric
    // slot independently, allowing either the texture or sampler half to be absent.
    std::bitset<GPUDevice::MAX_TEXTURE_SAMPLERS> bound_slots = {};
    for (const Binding& binding : pass.bindings)
    {
      GPUTexture* texture = nullptr;
      if (binding.has_texture)
      {
        // Can't bind the RT as a texture input. Keep the sampler half, if any,
        // because it occupies an independent register space on D3D11.
        if (std::any_of(pass.render_targets.begin(), pass.render_targets.end(),
                        [&binding](TextureID rt) { return rt == binding.texture_id; }))
        {
          GL_INS_FMT("Not binding RT texture {}: ID {} [{}]", binding.slot, binding.texture_id,
                     GetTextureNameForID(binding.texture_id));
        }
        else
        {
          texture = GetTextureByID(binding.texture_id, input_color, input_depth, final_target);
          GL_INS_FMT("Texture binding {}: ID {} [{}]", binding.slot, binding.texture_id,
                     GetTextureNameForID(binding.texture_id));
        }
      }

      g_gpu_device->SetTextureSampler(binding.slot, texture, binding.sampler);
      bound_slots[binding.slot] = true;
    }

    // Ensure RT wasn't left bound as a previous output, it breaks VK/DX12.
    // TODO: Maybe move this into the backend? Not sure...
    for (u32 i = 0; i < GPUDevice::MAX_TEXTURE_SAMPLERS; i++)
    {
      if (!bound_slots[i])
        g_gpu_device->SetTextureSampler(i, nullptr, nullptr);
    }

    g_gpu_device->Draw(pass.num_vertices, 0);
  }

  // Don't leave any textures bound.
  for (u32 i = 0; i < GPUDevice::MAX_TEXTURE_SAMPLERS; i++)
    g_gpu_device->SetTextureSampler(i, nullptr, nullptr);

  GL_POP();
  m_frame_timer.Reset();
  return true;
}
