// SPDX-FileCopyrightText: 2026 ArcadeDuck contributors
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#define ARCADEDUCK_PRODUCT_NAME "ArcadeDuck"
#define ARCADEDUCK_SEMANTIC_VERSION "0.3.0-dev"
#define ARCADEDUCK_BUILD_STRING "0001"
#define ARCADEDUCK_BUILD_NUMBER 1

#define ARCADEDUCK_FULL_DISPLAY_STRING \
  ARCADEDUCK_PRODUCT_NAME " " ARCADEDUCK_SEMANTIC_VERSION " (Build " ARCADEDUCK_BUILD_STRING ")"

#define ARCADEDUCK_WINDOWS_RESOURCE_VERSION 0,3,0,1
#define ARCADEDUCK_WINDOWS_RESOURCE_VERSION_DOTTED "0.3.0.1"

#define ARCADEDUCK_WINDOWS_RESOURCE_VERSION_DISPLAY \
  ARCADEDUCK_SEMANTIC_VERSION " (Build " ARCADEDUCK_BUILD_STRING ")"

#define ARCADEDUCK_GPL_BASELINE_HASH "25bc8a64803df7e702db66e0f11d7b7d0fdc99f2"
